name: 🏷️ Nightly Release Build

on:
  push:
    branches: [master]
    paths-ignore:
      - data/versions.json
      - docs/_static/switcher.json

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/release-check.yml

  release:
    name: 📦 Build Nightly Release
    needs: check
    if: ${{ needs.check.outputs.version_exists == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Git User
        uses: fregante/setup-git-user@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Cache Beet Content
        uses: actions/cache@v4
        with:
          path: .beet_cache
          key: ${{ runner.os }}-beet-cache
      - name: Build Release Files
        run: uv run modules release
      - name: Delete Existing Nightly Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete nightly --yes
          git push --delete origin nightly
      - name: Create New Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: docs/changelog/${{ needs.check.outputs.release_tag }}.md
          name: Nightly ${{ needs.check.outputs.release_name }}
          tag_name: nightly
          prerelease: true
          files: release/*.zip
